[package]
name = "xcom-1-card"
version = "0.1.0"
edition = "2021"
default-run = "main"

[lib]
name = "xcom_1_card"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
rand = "0.8"
indoc = "1.0"

[dev-dependencies]
test-case = "1.2.1"
